package BabAl.BabalServer.domain.enums;

public enum FoodCategoryName {
    FRUIT, SOUP, NOODLE, RICE, BREAD, RAW_VEGES, TEA, STIR_FRY, DAIRY_PRODS,
    SEASONED_VEGETABLES, KIMCHI, STEAMED, BOILED, FRIED, PORRIDGE, PANCAKE,
    SEASONING, FISH, NUT

}